# A default pyproject.toml for Pixi projects
[project]
# name = "my_project"
version = "0.1.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]
conda-pypi-map = { conda-forge = "https://raw.githubusercontent.com/prefix-dev/parselmouth/refs/heads/main/files/compressed_mapping.json", bioconda = "https://raw.githubusercontent.com/prefix-dev/parselmouth/refs/heads/main/files/compressed_mapping.json" }

[tool.pixi.dependencies]
python = "3.13.*"
numpy = ">=2.4.3,<3"
pandas = "2.*"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.17.1,<2"
statsmodels = ">=0.14.6,<0.15"
bcftools = ">=1.23.1,<2"
snakemake-minimal = "9.16.*"   # Breaking change in 9.17; reversed in 9.18
bedtools = ">=2.31.1,<3"
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"
ruff = ">=0.15.9,<0.16"
snakefmt = ">=1.0.0,<2"

[tool.pixi.pypi-dependencies]
# my_project = { path = ".", editable = true }
pandas-checks = '>=1.1.0,<2'
statannotations = '>=0.7.2,<0.8'
adjusttext = ">=1.3.0,<2"
ab_utils = { git = "https://github.com/alexblakes/ab_utils.git", branch = 'main' }

[tool.pixi.tasks]
ruff_lint = "ruff check --fix"
ruff_format = "ruff format"
smk_format = "snakefmt Snakefile workflow/"
fmt = { depends-on = ["ruff_lint", "ruff_format", "smk_format"] }
smk = "snakemake --cores 4"
dir_general = "mkdir -p data/{raw,interim,final,manual,external,scratch} log scripts"
dir_package = { args = [
    "package_name",
], cmd = "mkdir -p src/{{ package_name }}" }
init_package = { args = [
    "package_name",
], cmd = "touch src/{{ package_name }}/__init__.py" }

[tool.pixi.tasks.setup]
args = ["package_name"]
depends-on = [
    { task = "dir_general" },
    { task = "dir_package", args = [
        "{{ package_name }}",
    ] },
    { task = "init_package", args = [
        "{{ package_name }}",
    ] },
]
